sudo: required
dist: centos/7
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo yum update -y
  - sudo yum install -y docker-engine

install:
  - sudo pip install docker-py
    # software-properties-common for ubuntu 14.04
    # python-software-properties for ubuntu 12.04
  - sudo yum install -y sshpass software-properties-common python-software-properties
  - sudo pip install ansible
  - ansible --version

script:
  - ansible-playbook -i test/inventory test/test.yml
  - sudo cat /etc/motd
